dist: bionic

services:
  - docker

language: go

go:
  - "1.13"

env:
  global:
    - GO111MODULE=on
  matrix:
    - DOCKER_IMAGE=wsinpg/ub-12.04-irods-4.1:latest
    - DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2:latest

matrix:
  allow_failures:
    - env: DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2:latest

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a

install:
  - ./scripts/travis_install.sh

script:
  - ./scripts/travis_script.sh

